services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: git.osfb.dev
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        registry_external_url 'https://registry.git.osfb.dev'
        gitlab_rails['registry_enabled'] = true
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false

        external_url 'https://git.osfb.dev'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
    ports:
      - "5000:5050"
      - "8000:80"
      - "22:22"
    volumes:
      - /tb_storage/gitlab/config:/etc/gitlab
      - /tb_storage/gitlab/data:/var/opt/gitlab
      - /tb_storage/gitlab/logs:/var/log/gitlab
    networks:
      - gitlab_net

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - /tb_storage/runner/config/:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_net

networks:
  gitlab_net:
